[package]
name = "logpose"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
diesel = { version = "2.3.11", features = ["chrono", "postgres", "r2d2", "serde_json", "uuid"] }
dotenvy = "0.15.7"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
pq-sys = { version = "0.7.5", features = ["bundled_without_openssl"] }
chrono = { version = "0.4.45", features = ["serde"] }
uuid = { version = "1.24.0", features = ["serde", "v4"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
hex = "0.4.3"
base62 = "2.2.4"
fpe = "0.6.1"
aes = "0.8.4"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
argon2 = "0.5.3"
rand_core = { version = "0.6", features = ["getrandom"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
woothee = { version = "0.13.0", features = ["serde", "serde_derive"] }
redis = { version = "1.5.0", features = ["aio", "connection-manager", "tokio-comp"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tower-http = { version = "0.7.0", features = ["cors"] }
tower = { version = "0.5.3", features = ["balance", "limit", "load"] }
qrcode = "0.14.1"
hmac = "0.13.0"
sha2 = "0.11.0"
razorpay-rs = "0.1.0-alpha.1"
thiserror = "2.0.20"
async-trait = "0.1.92"
serde_json = "1.0.151"
oauth2 = "4.4"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }

[workspace]
