[package]
name = "logpose"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
diesel = { version = "2.3.11", features = ["chrono", "postgres", "r2d2", "serde_json", "uuid"] }
dotenvy = "0.15.7"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
pq-sys = { version = "0.7.5", features = ["bundled_without_openssl"] }
chrono = { version = "0.4.45", features = ["serde"] }
uuid = { version = "1.24.0", features = ["serde", "v4"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
md-5 = "0.11.0"
hex = "0.4.3"
base62 = "2.2.4"
fpe = "0.6.1"
aes = "0.8.4"
jsonwebtoken = "11.0.0"
argon2 = "0.5.3"
rand_core = { version = "0.6", features = ["getrandom"] }

[workspace]

