services:
  frontend:
    image: ghcr.io/swar09/logpose-frontend:latest
    container_name: logpose-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    env_file:
      - ../logpose-front-end/.env
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: ghcr.io/swar09/logpose-backend:latest
    container_name: logpose-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_ADDR: redis://:${REDIS_PASSWORD}@redis:6379
      SERVER_URL: "0.0.0.0:8000"
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17-alpine
    container_name: url-shortner-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: logpose-cloudflared
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --protocol http2 --edge-ip-version 4 --no-autoupdate run
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: