INSERT INTO plans (
    code,
    name,
    description,
    amount,
    currency,
    interval,
    max_urls_limit,
    custom_alias_allowed,
    analytics_retention_days,
    features,
    is_active
  )
VALUES (
    'plan_free',
    'Free',
    'Try it out, no cost',
    0,
    'USD',
    'monthly',
    50,
    false,
    30,
    '{
      "tagline": "Try it out, no cost",
      "monthly_price_usd": 0,
      "annual_price_usd": 0,
      "effective_monthly_usd": 0.00,
      "links_per_month": 50,
      "custom_alias_allowed": false,
      "qr_code_generator": true,
      "link_editing": false,
      "tracked_clicks_monthly": 1000,
      "analytics_history_days": 30,
      "bulk_creation": false,
      "api_access": "Limited",
      "team_seats": 1,
      "password_protected_links": false,
      "link_expiration_rules": "No",
      "support_level": "Community / Help Center"
    }'::jsonb,
    true
  ),
  (
    'plan_pro',
    'Pro',
    'For individuals & small projects',
    500,
    'USD',
    'monthly',
    1000,
    true,
    365,
    '{
      "tagline": "For individuals & small projects",
      "monthly_price_usd": 5,
      "annual_price_usd": 50,
      "effective_monthly_usd": 4.17,
      "links_per_month": 1000,
      "custom_alias_allowed": true,
      "qr_code_generator": true,
      "link_editing": true,
      "tracked_clicks_monthly": 25000,
      "analytics_history_days": 365,
      "bulk_creation": false,
      "api_access": "Standard",
      "team_seats": 1,
      "password_protected_links": false,
      "link_expiration_rules": "Basic",
      "support_level": "Email Support"
    }'::jsonb,
    true
  ),
  (
    'plan_pro_yearly',
    'Pro Annual',
    'For individuals & small projects',
    5000,
    'USD',
    'yearly',
    1000,
    true,
    365,
    '{
      "tagline": "For individuals & small projects",
      "monthly_price_usd": 5,
      "annual_price_usd": 50,
      "effective_monthly_usd": 4.17,
      "links_per_month": 1000,
      "custom_alias_allowed": true,
      "qr_code_generator": true,
      "link_editing": true,
      "tracked_clicks_monthly": 25000,
      "analytics_history_days": 365,
      "bulk_creation": false,
      "api_access": "Standard",
      "team_seats": 1,
      "password_protected_links": false,
      "link_expiration_rules": "Basic",
      "support_level": "Email Support"
    }'::jsonb,
    true
  ),
  (
    'plan_ultra',
    'Ultra',
    'For growing brands & creators',
    2000,
    'USD',
    'monthly',
    10000,
    true,
    730,
    '{
      "tagline": "For growing brands & creators",
      "monthly_price_usd": 20,
      "annual_price_usd": 150,
      "effective_monthly_usd": 12.50,
      "links_per_month": 10000,
      "custom_alias_allowed": true,
      "qr_code_generator": true,
      "link_editing": true,
      "tracked_clicks_monthly": 250000,
      "analytics_history_days": 730,
      "bulk_creation": true,
      "api_access": "Standard",
      "team_seats": 5,
      "password_protected_links": true,
      "link_expiration_rules": "Advanced",
      "support_level": "Priority Email Support"
    }'::jsonb,
    true
  ),
  (
    'plan_ultra_yearly',
    'Ultra Annual',
    'For growing brands & creators',
    15000,
    'USD',
    'yearly',
    10000,
    true,
    730,
    '{
      "tagline": "For growing brands & creators",
      "monthly_price_usd": 20,
      "annual_price_usd": 150,
      "effective_monthly_usd": 12.50,
      "links_per_month": 10000,
      "custom_alias_allowed": true,
      "qr_code_generator": true,
      "link_editing": true,
      "tracked_clicks_monthly": 250000,
      "analytics_history_days": 730,
      "bulk_creation": true,
      "api_access": "Standard",
      "team_seats": 5,
      "password_protected_links": true,
      "link_expiration_rules": "Advanced",
      "support_level": "Priority Email Support"
    }'::jsonb,
    true
  ) ON CONFLICT (code) DO
UPDATE
SET name = EXCLUDED.name,
  description = EXCLUDED.description,
  amount = EXCLUDED.amount,
  currency = EXCLUDED.currency,
  interval = EXCLUDED.interval,
  max_urls_limit = EXCLUDED.max_urls_limit,
  custom_alias_allowed = EXCLUDED.custom_alias_allowed,
  analytics_retention_days = EXCLUDED.analytics_retention_days,
  features = EXCLUDED.features,
  is_active = EXCLUDED.is_active,
  updated_at = CURRENT_TIMESTAMP;